#!/bin/bash

# from https://www.reddit.com/r/hyprland/comments/16skqzv/i_make_a_shell_script_that_control_wlsunset_from/

# Source the sunvar.sh script to get the variable
source ./sunvar.sh

# Check if the variable is set. If not, set it to 3500
if [ -z "$VAR" ]
then
    VAR=3500
fi

# Decrease the variable by 100, but not less than 1200
if ((VAR > 1200))
then
    VAR=$((VAR - 200))
fi

# Update the variable in sunvar.sh
echo "VAR=$VAR" > ./sunvar.sh

# Print the new value of VAR
echo "New value of VAR: $VAR"

# Check if wlsunset is running
if pgrep -x "wlsunset" > /dev/null
then
    # If wlsunset is running, kill it
    pkill -9 "wlsunset"
fi

# Run wlsunset with the new value
wlsunset -t $VAR
