#!/bin/bash

# from https://www.reddit.com/r/hyprland/comments/16skqzv/i_make_a_shell_script_that_control_wlsunset_from/

if pgrep -x "wlsunset" > /dev/null
then
    pkill wlsunset
else
    wlsunset
fi
