#!/bin/bash

# from https://www.reddit.com/r/hyprland/comments/16skqzv/i_make_a_shell_script_that_control_wlsunset_from/

if [ "$(hyprctl hyprsunset temperature)" = "6000" ];
then
    hyprctl hyprsunset temperature 4000
else
    hyprctl hyprsunset temperature 6000
fi
